// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN-wnenrTMnD5h4D1KQrbHz_Ub-xZ02JE',
    appId: '1:867535340801:web:fb0fe435eeb9e0912dc700',
    messagingSenderId: '867535340801',
    projectId: 'quotation-eee9e',
    authDomain: 'quotation-eee9e.firebaseapp.com',
    databaseURL: 'https://quotation-eee9e.firebaseio.com',
    storageBucket: 'quotation-eee9e.appspot.com',
    measurementId: 'G-0GWENL3ZZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs2aubV0qHxpw9tU7jSb3WDPcNfWkjftc',
    appId: '1:867535340801:android:6f4a2b1bd01d855f2dc700',
    messagingSenderId: '867535340801',
    projectId: 'quotation-eee9e',
    databaseURL: 'https://quotation-eee9e.firebaseio.com',
    storageBucket: 'quotation-eee9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPM6dRe8lBlC7Fx-Vu-nc8s_udQxmbekE',
    appId: '1:867535340801:ios:47d297e8df2a078e2dc700',
    messagingSenderId: '867535340801',
    projectId: 'quotation-eee9e',
    databaseURL: 'https://quotation-eee9e.firebaseio.com',
    storageBucket: 'quotation-eee9e.appspot.com',
    iosClientId: '867535340801-vjnces966gf3pkf7ifs36iu23l2qdv4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.joinquotation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPM6dRe8lBlC7Fx-Vu-nc8s_udQxmbekE',
    appId: '1:867535340801:ios:47d297e8df2a078e2dc700',
    messagingSenderId: '867535340801',
    projectId: 'quotation-eee9e',
    databaseURL: 'https://quotation-eee9e.firebaseio.com',
    storageBucket: 'quotation-eee9e.appspot.com',
    iosClientId: '867535340801-vjnces966gf3pkf7ifs36iu23l2qdv4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.joinquotation',
  );
}
